Building with stock GCC/G++ 15.1.0.
I built from source a GCC/G++ 15.1.0 compiler to debug the CI failures
for #363 locally. Though, our compiler won't build with a stock
GCC/G++ 15.1.0 compiler. I hit the following compilation error:

```console
libs/compiler/src/monad/vm/compiler/ir/poly_typed/kind.hpp:163:20: error: missing template arguments before ‘(’ token
  163 |         format_kind(kind, ctx, false);
```

The culprit appears to be [this
file](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/format)
in the GCC distribution, which is part of the stock GCC/G++ include
path. It contains a templated member `format_kind`, which appears to
be shadowing the `format_kind` in the `kind.hpp` file.

A workaround is to fully qualify invocation of `format_kind`. For good
measure, I have fully qualified the call to `format_cont` too.

I am not sure why the shadowing is happening. Perhaps it is indicative of an inadvertent opening of the `std` namespace somewhere, or perhaps it has something to do with the default configuration of GCC/G++ 15.1.0.